#
# This is an example file for docker-compose
#
version: '3'
services:
  mysql-1:
    image: "appsdevteam/innodb-cluster"
    restart: always
    hostname: mysql-1
    environment:
      - "MYSQL_ROOT_PASSWORD=spew-sorority-rancour"
      - "GROUP_NAME=C55153C1-1574-4972-BF06-7332D6AD46A7"
      - "BOOTSTRAP=1"
      - "LOCAL_ADDRESS=mysql-1"
    volumes:
      - ./data/mysql-1:/var/lib/mysql
  mysql-2:
    image: "appsdevteam/innodb-cluster"
    restart: always
    hostname: mysql-2
    environment:
      - "MYSQL_ROOT_PASSWORD=spew-sorority-rancour"
      - "GROUP_NAME=C55153C1-1574-4972-BF06-7332D6AD46A7"
      - "GROUP_SEEDS=mysql-1:6606,mysql-3:6606"
      - "LOCAL_ADDRESS=mysql-2"
    volumes:
      - ./data/mysql-2:/var/lib/mysql
    depends_on:
      - mysql-1
  mysql-3:
    image: "appsdevteam/innodb-cluster"
    restart: always
    hostname: mysql-3
    environment:
      - "MYSQL_ROOT_PASSWORD=spew-sorority-rancour"
      - "GROUP_NAME=C55153C1-1574-4972-BF06-7332D6AD46A7"
      - "GROUP_SEEDS=mysql-1:6606,mysql-2:6606"
      - "LOCAL_ADDRESS=mysql-3"
    volumes:
      - ./data/mysql-3:/var/lib/mysql
    depends_on:
      - mysql-1
  router:
    image: "mattalord/innodb-cluster"
    restart: always
    hostname: router
    ports:
      - "3306:3306"
      - "6606:6606"
      - "6446-6447:6446-6447"
    volumes:
      - ./data/mysql-router:/var/lib/mysqlrouter
    depends_on:
      - mysql-1
      - mysql-2
      - mysql-3
    environment:
      - "NODE_TYPE=router"
      - "MYSQL_ROOT_PASSWORD=spew-sorority-rancour"
      - "MYSQL_HOST=mysql-1"
